import { Category, Business } from './types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Restaurantes y Comida' },
  { id: 2, name: 'Salud y Bienestar' },
  { id: 3, name: 'Servicios Profesionales' },
  { id: 4, name: 'Compras y Tiendas' },
  { id: 5, name: 'Automotriz' },
  { id: 6, name: 'Hogar y Jardín' },
];

// Helper to create future dates for promotions
const createEndDate = (months: number): string => {
  const date = new Date();
  date.setMonth(date.getMonth() + months);
  return date.toISOString();
};


export const BUSINESSES: Business[] = [
  {
    id: 1,
    name: "Tacos 'El Padrino'",
    description: "Los mejores tacos al pastor de la región. Sabor tradicional y auténtico con ingredientes frescos. ¡Visítanos y prueba nuestra famosa salsa secreta!",
    logoUrl: "https://i.pravatar.cc/150?u=tacos",
    phone: "5511223344",
    whatsapp: "5215511223344",
    website: "https://tacos-el-padrino.com",
    categoryId: 1,
    services: ["Tacos al Pastor", "Gringas", "Alambres"],
    products: ["Refrescos", "Aguas Frescas"],
    isFeatured: true,
    ownerName: "Carlos Pérez",
    ownerEmail: "carlos.perez@example.com",
    isActive: true,
    promotionEndDate: createEndDate(3),
  },
  {
    id: 2,
    name: "Clínica Dental Sonrisa Feliz",
    description: "Cuidamos tu salud bucal con la mejor tecnología y un equipo de especialistas. Ofrecemos ortodoncia, implantes, blanqueamiento y más.",
    logoUrl: "https://i.pravatar.cc/150?u=dental",
    phone: "5522334455",
    whatsapp: "5215522334455",
    website: "https://sonrisafeliz.com",
    categoryId: 2,
    services: ["Limpieza Dental", "Blanqueamiento", "Ortodoncia", "Implantes"],
    products: [],
    isFeatured: true,
    ownerName: "Dra. Ana Gómez",
    ownerEmail: "ana.gomez@example.com",
    isActive: true,
    promotionEndDate: createEndDate(6),
  },
  {
    id: 3,
    name: "Abogados y Consultores Izcalli",
    description: "Asesoría legal confiable y profesional. Especialistas en derecho civil, mercantil y familiar. Protegemos tus intereses con ética y experiencia.",
    logoUrl: "https://i.pravatar.cc/150?u=abogados",
    phone: "5533445566",
    whatsapp: "5215533445566",
    website: "https://abogadosizcalli.com",
    categoryId: 3,
    services: ["Asesoría Legal", "Contratos", "Litigios"],
    products: [],
    isFeatured: false,
    ownerName: "Lic. Roberto Díaz",
    ownerEmail: "roberto.diaz@example.com",
    isActive: true,
    promotionEndDate: createEndDate(1),
  },
  {
    id: 4,
    name: "Boutique 'La Elegancia'",
    description: "Moda para dama y caballero con las últimas tendencias. Encuentra el outfit perfecto para cada ocasión. Calidad y estilo a tu alcance.",
    logoUrl: "https://i.pravatar.cc/150?u=boutique",
    phone: "5544556677",
    whatsapp: "5215544556677",
    website: "https://la-elegancia.com",
    categoryId: 4,
    services: ["Venta de Ropa", "Asesoría de Imagen"],
    products: ["Vestidos", "Trajes", "Accesorios"],
    isFeatured: true,
    ownerName: "Sofía Martínez",
    ownerEmail: "sofia.martinez@example.com",
    isActive: true,
    promotionEndDate: createEndDate(12),
  },
  {
    id: 5,
    name: "Taller Mecánico 'El Rápido'",
    description: "Servicio automotriz de confianza. Hacemos afinaciones, cambio de aceite, frenos y diagnóstico por computadora. ¡Tu auto en las mejores manos!",
    logoUrl: "https://i.pravatar.cc/150?u=mecanico",
    phone: "5555667788",
    whatsapp: "5215555667788",
    website: "https://taller-el-rapido.com",
    categoryId: 5,
    services: ["Afinación", "Frenos", "Cambio de Aceite", "Suspensión"],
    products: ["Refacciones", "Aditivos"],
    isFeatured: false,
    ownerName: "Jorge Hernández",
    ownerEmail: "jorge.hernandez@example.com",
    isActive: false,
    promotionEndDate: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(), // Expired
  },
  {
    id: 6,
    name: "Vivero y Jardinería 'El Edén'",
    description: "Todo lo que necesitas para tu jardín. Plantas de ornato, árboles frutales, macetas, tierra y herramientas. Creamos espacios verdes y llenos de vida.",
    logoUrl: "https://i.pravatar.cc/150?u=vivero",
    phone: "5566778899",
    whatsapp: "5215566778899",
    website: "https://vivero-el-eden.com",
    categoryId: 6,
    services: ["Diseño de Jardines", "Mantenimiento", "Venta de Plantas"],
    products: ["Macetas", "Tierra Preparada", "Fertilizantes"],
    isFeatured: false,
    ownerName: "Laura Torres",
    ownerEmail: "laura.torres@example.com",
    isActive: true,
    promotionEndDate: createEndDate(2),
  }
];
