import { Business, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Restaurantes y Comida' },
  { id: 2, name: 'Salud y Belleza' },
  { id: 3, name: 'Servicios Profesionales' },
  { id: 4, name: 'Tiendas y Comercios' },
  { id: 5, name: 'Automotriz' },
  { id: 6, name: 'Hogar y Jardín' },
];

export const BUSINESSES: Business[] = [
  {
    id: 1,
    name: 'Taquería "El Buen Pastor"',
    logoUrl: 'https://picsum.photos/seed/tacos/400/400',
    description: 'Los mejores tacos al pastor de Izcalli. Tradición y sabor en cada bocado desde 1998.',
    services: ['Servicio a domicilio', 'Eventos privados', 'Pedidos para llevar'],
    products: ['Tacos al pastor', 'Gringas', 'Alambres', 'Costras', 'Aguas frescas'],
    categoryId: 1,
    phone: '5512345678',
    whatsapp: '5215512345678',
    website: 'https://elbuenpastor.com',
    isFeatured: true,
  },
  {
    id: 2,
    name: 'Salón de Belleza "Estilo Divino"',
    logoUrl: 'https://picsum.photos/seed/salon/400/400',
    description: 'Expertos en colorimetría y cuidado del cabello. Te ayudamos a encontrar tu mejor versión.',
    services: ['Corte de cabello', 'Tinte y mechas', 'Manicure y pedicure', 'Maquillaje profesional'],
    products: ['Shampoos especializados', 'Tratamientos capilares', 'Esmaltes de uñas'],
    categoryId: 2,
    phone: '5523456789',
    whatsapp: '5215523456789',
    website: 'https://estilodivino.mx',
    isFeatured: true,
  },
  {
    id: 3,
    name: 'Consultores Legales "Izcalli Abogados"',
    logoUrl: 'https://picsum.photos/seed/law/400/400',
    description: 'Asesoría legal confiable y profesional en materia civil, penal y mercantil.',
    services: ['Asesoría jurídica', 'Representación en litigios', 'Elaboración de contratos', 'Gestión de trámites'],
    products: [],
    categoryId: 3,
    phone: '5534567890',
    whatsapp: '5215534567890',
    website: 'https://izcalliabogados.com',
    isFeatured: false,
  },
  {
    id: 4,
    name: 'Refaccionaria "El Pistón Veloz"',
    logoUrl: 'https://picsum.photos/seed/autoparts/400/400',
    description: 'Amplio surtido en refacciones para todas las marcas. Calidad y buenos precios garantizados.',
    services: ['Asesoría técnica', 'Entrega a domicilio'],
    products: ['Frenos', 'Suspensiones', 'Filtros', 'Aceites', 'Baterías'],
    categoryId: 5,
    phone: '5545678901',
    whatsapp: '5215545678901',
    website: 'https://elpistonveloz.com',
    isFeatured: true,
  },
  {
    id: 5,
    name: 'Café "Aroma del Bosque"',
    logoUrl: 'https://picsum.photos/seed/coffee/400/400',
    description: 'Un espacio acogedor para disfrutar de café de especialidad y postres artesanales.',
    services: ['Wi-Fi gratuito', 'Área de trabajo'],
    products: ['Espresso', 'Cappuccino', 'Frappés', 'Cheesecakes', 'Paninis'],
    categoryId: 1,
    phone: '5556789012',
    whatsapp: '5215556789012',
    website: 'https://cafearomadelbosque.com',
    isFeatured: false,
  },
  {
    id: 6,
    name: 'Florería "Jardín Secreto"',
    logoUrl: 'https://picsum.photos/seed/flowers/400/400',
    description: 'Arreglos florales para toda ocasión. Expresa tus sentimientos con la belleza de las flores.',
    services: ['Diseño de arreglos personalizados', 'Decoración de eventos', 'Entrega el mismo día'],
    products: ['Ramos de rosas', 'Arreglos fúnebres', 'Plantas de ornato', 'Peluches y globos'],
    categoryId: 6,
    phone: '5567890123',
    whatsapp: '5215567890123',
    website: 'https://jardinsecreto.mx',
    isFeatured: true,
  },
  {
    id: 7,
    name: 'La Casa del Tornillo',
    logoUrl: 'https://picsum.photos/seed/hardware/400/400',
    description: 'Ferretería y tlapalería con el más extenso surtido en tornillería y herramientas.',
    services: ['Venta al mayoreo y menudeo'],
    products: ['Tornillos', 'Tuercas', 'Herramientas manuales', 'Herramientas eléctricas', 'Pintura'],
    categoryId: 4,
    phone: '5578901234',
    whatsapp: '5215578901234',
    website: 'https://casadeltornillo.com',
    isFeatured: false,
  },
  {
    id: 8,
    name: 'Clínica Dental "Sonrisa Perfecta"',
    logoUrl: 'https://picsum.photos/seed/dental/400/400',
    description: 'Odontología integral para toda la familia. Tecnología de punta y atención personalizada.',
    services: ['Limpieza dental', 'Blanqueamiento', 'Ortodoncia', 'Implantes dentales'],
    products: [],
    categoryId: 2,
    phone: '5589012345',
    whatsapp: '5215589012345',
    website: 'https://sonrisaperfectaizcalli.com',
    isFeatured: false,
  }
];
